name: CI

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  job-install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Caching dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Install Dependencies
        if: steps.cache-dependencies.output.cache-hit != 'true'
        run: yarn

      - name: Run Lint
        run: yarn lint

      - name: Run Type Check
        run: yarn tsc
